version: "3.7"
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres@postgres/myapp_development
      - DATABASE_HOST=postgres
    depends_on:
      - postgres

volumes:
  postgres_data_test: